# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 6s"
])

languages([
  "en-US"
])

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# The name of the scheme which contains the UI Tests
scheme "storefront-iosUIFunctionalTests"

# Where should the resulting screenshots be stored?
output_directory "./screenshots"

clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./Project.xcodeproj"
workspace "./merchant-ios.xcworkspace"

# For more information about all available options run
# snapshot --help

ios_version "10.1"
reinstall_app true
erase_simulator false
skip_open_summary true
configuration "Debug"
number_of_retries 0
derived_data_path "derived_data_path"
app_identifier "com.mm.storefront"
launch_arguments([
"-username perm-mm -password Bart"
])
